services:
    jenkins:
        image: jenkins/jenkins:lts
        container_name: jenkins
        restart: always
        user: root
        ports:
            - "8080:8080"
            - "50000:50000"
        volumes:
            - jenkins_home:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    grafana:
        image: grafana/grafana
        container_name: grafana
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - grafana_data:/var/lib/grafana
volumes:
    jenkins_home:
        driver: local
    grafana_data:
        driver: local
