services:
    jenkins:
        image: jenkins/jenkins:lts
        container_name: jenkins
        restart: always
        user: root
        ports:
            - "18080:8080"
            - "50000:50000"
        volumes:
            - jenkins_home:/var/jenkins_home
            - ./init.groovy.d:/var/jenkins_home/init.groovy.d
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    grafana:
        image: grafana/grafana
        container_name: grafana
        restart: always
        ports:
            - "13000:3000"
        volumes:
            - grafana_data:/var/lib/grafana
            - ./provisioning:/etc/grafana/provisioning
            - ./provisioning/dashboards:/etc/grafana/provisioning/dashboards
            - ./dashboards:/var/lib/grafana/dashboards
        environment:
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=admin
        depends_on:
            - prometheus
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        restart: always
        user: root
        ports:
            - "19090:9090"
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
            - ./prometheus_data:/prometheus
volumes:
    jenkins_home:
        driver: local
    grafana_data:
        driver: local
    prometheus_data:
        driver: local
