services:
    clientwebsocketgithubtrigger:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: clientWebsocketGithubTrigger
        restart: always
        ports:
            - "28081:8080"
